jobs:
     build:
          runs-on: ubuntu-20.04
          steps: 
               - uses: actions/checkout@v2.3.1
               - run: dotnet build # compile
     test:
          runs-on: ubuntu-20.04
          steps:
               - uses: actions/checkout@v2.3.1
               - run: dotnet test -p:CollectCoverage=true
     analyze:
          needs: [build, test] #another way to write collection
          runs-on: ubuntu-20.04
          steps:
               - uses: actions/checkout@v2.3.1
               - run: dotnet tool install --global dotnet-sonarscanner --version 4.10.0
               - run: |
                    dotnet sonarscanner begin -o:'kguers' -k:'kguers_training-code-wk4' -d:sonar.login='064daeeda3fc032eed41a03552d337bf81216545' -d:sonar.host.url='https://sonarcloud.io/'
                    dotnet build
                    dotnet test -p:CollectCoverage=true
                    dotnet sonarscanner end -d:sonar.login='064daeeda3fc032eed41a03552d337bf81216545'
               env: 
                    GITHUB_TOKEN: {{secrets.GITHUB_TOKEN}}
     # package:
     # deploy:

name: cibuild

on: push






#HOW TO YAML
# person: #object
#      firstName: 'Kyle' # string
#      lastName: 100 # number
#      middleName: true # boolean
#      alias: #collection
#           - 'dotnet'
#           - 'lead'
#           - subAlias: #object within collection (not recommended)
