jobs:
     build:
          runs-on: ubuntu-20.04
          steps: 
               - uses: actions/checkout@v2.3.1
               - run: dotnet build
     test:
          runs-on: ubuntu-20.04
          steps:
               - uses: actions/checkut@v2.3.1
               - run: dotnet test
     # analyze:
     # package:
     # deploy:

name: cibuild

on: push






#HOW TO YAML
# person: #object
#      firstName: 'Kyle' # string
#      lastName: 100 # number
#      middleName: true # boolean
#      alias: #collection
#           - 'dotnet'
#           - 'lead'
#           - subAlias: #object within collection (not recommended)
